configured: true

server:
  url_flag_checker: "http://localhost:5001/flags"
  team_token: "c882674c6270b8293fff7f4fb5c4c249"
  submit_flag_checker_time: 120
  max_flag_batch_size: 1000
  protocol: "cc_http"
  tick_time: 120
  flag_ttl: 0 # in ticks
  start_time: "2023-10-01T00:00:00Z"
  end_time: "2023-10-31T23:59:59Z"

client:
  services:
    - name: "CookieService"
      port: 8081
    - name: "vulnify"
      port: 1337
    - name: "app-nc"
      port: 1338
  range_ip_teams: 29
  format_ip_teams: "10.10.{}.1"
  my_team_id: 1
  regex_flag: "[A-Z0-9]{31}="
  nop_team: 0
  url_flag_ids: "http://localhost:5001/flagIds"
