configured: true

server:
  host_flagchecker: "10.10.0.1:8080"
  team_token: "c882674c6270b8293fff7f4fb5c4c249"
  submit_flag_checker_time: 120
  max_flag_batch_size: 1000
  protocol: "cc_http"
  tick_time: 120
  start_time: "idk"

client:
  services:
    - name: "CookieService"
      port: 8081
  range_ip_teams: 29
  format_ip_teams: "10.10.{}.1"
  my_team_id: 1
  regex_flag: "[A-Z0-9]{31}="
  nop_team: 0
