configured: true

server:
  host_flagchecker: "10.10.0.1:8080"
  team_token: "c882674c6270b8293fff7f4fb5c4c249"
  submit_flag_checker_time: 120
  max_flag_batch_size: 1000
  protocol: "cc_http"

client:
  services:
    - name: "GadgetHorse"
      port: 3000
    - name: "CheesyCheats"
      port: 5555
    - name: "MineCClicker"
      port: 9999
    - name: "SeaOFHackerz"
      port: 5050
  range_ip_teams: 40
  format_ip_teams: "10.60.{}.1"
  my_team_ip: "10.60.0.1"
  regex_flag: "[A-Z0-9]{31}="
