services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PASSWORD: ${PASSWORD}
      CONFIG_FILE: ${CONFIG_FILE}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
    volumes:
      - sqlite_bp:/app/database
    networks:
      - cookiefarm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    profiles: ["full"]
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
    depends_on:
      - server
    networks:
      - cookiefarm-network

volumes:
  sqlite_bp:
    driver: local

networks:
  cookiefarm-network:
    driver: bridge
    name: cookiefarm-network
