services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: prod
  #   restart: unless-stopped
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     PASSWORD: ${PASSWORD}
  #     CONFIG_FILE: ${CONFIG_FILE}
  #     PORT: ${PORT}
  #     DEBUG: ${DEBUG}
  #   volumes:
  #     - sqlite_bp:/app/database
  #   networks:
  #     - cookiefarm-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
  #   depends_on:
  #     - server
  #   networks:
  #     - cookiefarm-network

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - cookiefarm-network

  redis-insights:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - cookiefarm-network

volumes:
  redis_data:
    driver: local
  sqlite_bp:
    driver: local

networks:
  cookiefarm-network:
    driver: bridge
    name: cookiefarm-network
