// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Flag struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Msg          string
	Status       string
	TeamID       int64
	Username     string
	ExploitName  string
}
