// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addFlags = `-- name: AddFlags :exec
INSERT OR IGNORE INTO flags(
	flag_code, service_name, port_service,
	submit_time, response_time, status,
	team_id, msg, username, exploit_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddFlagsParams struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) AddFlags(ctx context.Context, arg AddFlagsParams) error {
	_, err := q.db.ExecContext(ctx, addFlags,
		arg.FlagCode,
		arg.ServiceName,
		arg.PortService,
		arg.SubmitTime,
		arg.ResponseTime,
		arg.Status,
		arg.TeamID,
		arg.Msg,
		arg.Username,
		arg.ExploitName,
	)
	return err
}

const deleteFlagByCode = `-- name: DeleteFlagByCode :exec
DELETE FROM flags
WHERE flag_code = ?
`

func (q *Queries) DeleteFlagByCode(ctx context.Context, flagCode string) error {
	_, err := q.db.ExecContext(ctx, deleteFlagByCode, flagCode)
	return err
}

const deleteFlagByTTL = `-- name: DeleteFlagByTTL :exec
DELETE FROM flags
WHERE response_time < strftime('%s', 'now', ?)
`

func (q *Queries) DeleteFlagByTTL(ctx context.Context, strftime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteFlagByTTL, strftime)
	return err
}

const getFlagByCode = `-- name: GetFlagByCode :one
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
WHERE flag_code = ?
LIMIT 1
`

type GetFlagByCodeRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) GetFlagByCode(ctx context.Context, flagCode string) (GetFlagByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getFlagByCode, flagCode)
	var i GetFlagByCodeRow
	err := row.Scan(
		&i.FlagCode,
		&i.ServiceName,
		&i.PortService,
		&i.SubmitTime,
		&i.ResponseTime,
		&i.Status,
		&i.TeamID,
		&i.Msg,
		&i.Username,
		&i.ExploitName,
	)
	return i, err
}

const listAllFlagCodes = `-- name: ListAllFlagCodes :many
SELECT flag_code FROM flags
`

func (q *Queries) ListAllFlagCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllFlagCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFlags = `-- name: ListAllFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
ORDER BY submit_time DESC
`

type ListAllFlagsRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) ListAllFlags(ctx context.Context) ([]ListAllFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFlagsRow
	for rows.Next() {
		var i ListAllFlagsRow
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Status,
			&i.TeamID,
			&i.Msg,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFirstNFlagCodes = `-- name: ListFirstNFlagCodes :many
SELECT flag_code FROM flags
LIMIT ?
`

func (q *Queries) ListFirstNFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFirstNFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFirstNFlags = `-- name: ListFirstNFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
ORDER BY submit_time DESC
LIMIT ?
`

type ListFirstNFlagsRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) ListFirstNFlags(ctx context.Context, limit int64) ([]ListFirstNFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFirstNFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFirstNFlagsRow
	for rows.Next() {
		var i ListFirstNFlagsRow
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Status,
			&i.TeamID,
			&i.Msg,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlagsByTeam = `-- name: ListFlagsByTeam :many
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
WHERE team_id = ?
ORDER BY submit_time DESC
LIMIT ? OFFSET ?
`

type ListFlagsByTeamParams struct {
	TeamID int64
	Limit  int64
	Offset int64
}

type ListFlagsByTeamRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) ListFlagsByTeam(ctx context.Context, arg ListFlagsByTeamParams) ([]ListFlagsByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlagsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagsByTeamRow
	for rows.Next() {
		var i ListFlagsByTeamRow
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Status,
			&i.TeamID,
			&i.Msg,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagedFlagCodes = `-- name: ListPagedFlagCodes :many
SELECT flag_code FROM flags
LIMIT ? OFFSET ?
`

type ListPagedFlagCodesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPagedFlagCodes(ctx context.Context, arg ListPagedFlagCodesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPagedFlagCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagedFlags = `-- name: ListPagedFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
ORDER BY submit_time DESC
LIMIT ? OFFSET ?
`

type ListPagedFlagsParams struct {
	Limit  int64
	Offset int64
}

type ListPagedFlagsRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) ListPagedFlags(ctx context.Context, arg ListPagedFlagsParams) ([]ListPagedFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagedFlags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPagedFlagsRow
	for rows.Next() {
		var i ListPagedFlagsRow
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Status,
			&i.TeamID,
			&i.Msg,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsubmittedFlagCodes = `-- name: ListUnsubmittedFlagCodes :many
SELECT flag_code FROM flags
WHERE status = 'UNSUBMITTED'
LIMIT ?
`

func (q *Queries) ListUnsubmittedFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnsubmittedFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsubmittedFlags = `-- name: ListUnsubmittedFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, status, team_id, msg, username, exploit_name
FROM flags
WHERE status = 'UNSUBMITTED'
ORDER BY submit_time ASC
LIMIT ?
`

type ListUnsubmittedFlagsRow struct {
	FlagCode     string
	ServiceName  string
	PortService  int64
	SubmitTime   sql.NullInt64
	ResponseTime sql.NullInt64
	Status       string
	TeamID       int64
	Msg          string
	Username     string
	ExploitName  string
}

func (q *Queries) ListUnsubmittedFlags(ctx context.Context, limit int64) ([]ListUnsubmittedFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsubmittedFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsubmittedFlagsRow
	for rows.Next() {
		var i ListUnsubmittedFlagsRow
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Status,
			&i.TeamID,
			&i.Msg,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagStatusByCode = `-- name: UpdateFlagStatusByCode :exec
UPDATE flags
SET
	status = ?,
	msg = ?,
	response_time = ?
WHERE flag_code = ?
`

type UpdateFlagStatusByCodeParams struct {
	Status       string
	Msg          string
	ResponseTime sql.NullInt64
	FlagCode     string
}

func (q *Queries) UpdateFlagStatusByCode(ctx context.Context, arg UpdateFlagStatusByCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateFlagStatusByCode,
		arg.Status,
		arg.Msg,
		arg.ResponseTime,
		arg.FlagCode,
	)
	return err
}
