services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      dev: ${dev}
      PORT: ${PORT}
    volumes:
      - sqlite_bp:/app/database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      PORT: ${FRONTEND_PORT}
    volumes:
      - sqlite_bp:/app/db
volumes:
  sqlite_bp:
