services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PASSWORD: ${PASSWORD}
      CONFIG_FROM_FILE: ${CONFIG_FROM_FILE}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
    volumes:
      - sqlite_bp:/app/database

volumes:
  sqlite_bp:
