services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PASSWORD: ${PASSWORD}
      CONFIG_FROM_FILE: ${CONFIG_FROM_FILE}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
    volumes:
      - sqlite_bp:/app/database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - app

volumes:
  sqlite_bp:
