name: Sonar Qube Scan + tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fix shallow clone warning

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: cookiefarm/server/go.sum

      - name: Install gocover-cobertura
        run: go install github.com/boumenot/gocover-cobertura@latest

      - name: Run tests & generate coverage
        working-directory: cookiefarm/server
        run: |
          mkdir -p ./coverage
          go test -coverprofile=./coverage/coverage.out -v ./...
          gocover-cobertura < ./coverage/coverage.out > ./coverage/coverage.xml

      - name: SonarQube Scan CookieFarm
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
